version: 2

sphinx:
  configuration: docs/source/conf.py


python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
    rust: "1.64"
    golang: "1.19"