version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.11"
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04  # This is the correct value for Read the Docs